included:
  - Test-CI
excluded:
  - Test-CITests
  - Pods
  - fastlane
opt_in_rules:
  - array_init
  - block_based_kvo
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_optional_boolean
  - dynamic_inline
  - empty_count
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - for_where
  - force_try
  - force_unwrapping
  - implicit_getter
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - literal_expression_end_indentation
  - mark
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - weak_delegate
  - yoda_condition




disabled_rules:
 - class_delegate_protocol
 - conditional_returns_on_newline
 - contains_over_first_not_nil
 - discouraged_object_literal
 - explicit_acl
 - explicit_enum_raw_value
 - explicit_top_level_acl
 - explicit_type_interface
 - extension_access_modifier
 - force_cast
 - function_parameter_count
 - generic_type_name
 - is_disjoint
 - let_var_whitespace
 - line_length
 - nesting
 - nimble_operator
 - no_extension_access_modifier
 - no_grouping_extension
 - number_separator
 - object_literal
 - override_in_extension
 - pattern_matching_keywords
 - prefixed_toplevel_constant
 - private_action
 - private_outlet
 - private_over_fileprivate
 - private_unit_test
 - prohibited_super_call
 - protocol_property_accessors_order
 - required_enum_case
 - sorted_imports
 - strict_fileprivate
 - switch_case_on_newline
 - todo
 - trailing_closure
 - trailing_whitespace
 - type_name
 - unneeded_break_in_switch 
 - valid_ibinspectable
 - void_return
 - xctfail_message
 - implicit_return
 - empty_enum_arguments
 - identifier_name

function_body_length:
- 30 #warning
- 100 #error

cyclomatic_complexity:
- 5 #warning


