# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
clear_derived_data
end

platform :ios do
  desc "Description of what the lane does"
  lane :code_coverage do
    scan(scheme: "CI-test", code_coverage: true, output_directory: "./reports", disable_xcpretty: false)
    # slather(cobertura_xml: true, jenkins: true, scheme: "CI-test", proj: "./CI-test.xcodeproj")
    # lizard(source_folder: "CI-test", language: "swift,objectivec", export_type: "xml", report_file: "lizard-report.xml")
    # swiftlint(output_file: "swiftlint.txt", ignore_exit_status: true)
    # xcov(
    #   workspace: "CI-test.xcworkspace",
    #   scheme: "CI-test",
    #   output_directory: "xcov_output"
    # )
    danger(
      danger_id: "metrics",
      dangerfile: "Dangerfile",
      verbose: true
    )
  end
end
