name: code_coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  metrics:
    name: Run Metrics
    runs-on: [self-hosted]

    steps:
    - name: Show PR number
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_BASE: ${{ github.event.pull_request.base.ref }}
        PR_HEAD: ${{ github.event.pull_request.head.ref }}
      run: echo "The PR number is $PR_NUMBER, the base is $PR_BASE, the head is $PR_HEAD"

    - uses: actions/checkout@v2
    - uses: maierj/fastlane-action@v2.0.0
      with:
        lane: 'code_coverage'
        subdirectory: 'ios'
    # - name: Run Metrics through fastlane
    #   run: bundle exec fastlane code_coverage
